/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "var(--primary)",
        primaryDark: "var(--primary-dark)",
        primaryLight: "var(--primary-light)",
        secondary: "var(--secondary)",
        backgroundDark: "var(--background-dark)",
        backgroundLight: "var(--background-light)",
        fontLight: "var(--font-light)",
        fontDark: "var(--font-dark)",
        special: "var(--special)",
        A: "#3B8E8E",
        B: "#3C3B8E",
        C: "#8E3B64",
        D: "#648E3B",
        E: "#667FAA",
        F: "#34346B",
        G: "#346B6B",
        H: "#6B344F",
        I: "#F79DD8",
        J: "#1E354D",
        K: "#648E3B",
        L: "#3C3B8E",
        M: "#3B8E8E",
        N: "#667FAA",
        O: "#3C3B8E",
        P: "#F3CCEA",
        Q: "#1E354D",
        R: "#D18CB4",
        S: "#BB7A9F",
        T: "#667FAA",
        U: "#3C3B8E",
        V: "#F79DD8",
        W: "#667FAA",
        X: "#4E2436",
        Y: "#3C3B8E",
        Z: "#3B8E8E"
      },
    },
  },
  plugins: [],
};
